window.PORTFOLIO_STATIC_CONTENT = {
  "profile": {
    "name": "王俊博",
    "role": "摄像 / 后期剪辑 / 媒体内容制作",
    "jobTarget": "摄像师 / 后期剪辑师 / 新媒体视觉",
    "city": "接受外出拍摄",
    "education": "辽宁工程技术大学 / 广播电视学 / 2025届本科",
    "experience": "2024.05 - 至今，摄像 / 后期 / 新闻",
    "tools": "DaVinci / After Effects / 剪映 / DJI / SONY",
    "contact": "15640361376",
    "intro": "适合岗位：摄像师 / 后期剪辑师 / 视频内容创作 / 新媒体视觉。自我评价性格开朗善于沟通，无不良嗜好，不抽烟不喝酒，热爱深度内容，喜爱电影 阅读 也关注人物、社会议题与具有深度表达的内容，希望在影像工作中持续提升自己的能力，观察力、表达力和审美判断。\n热衷于持续学习各种前沿领域，善于学习运用ai工具，该网站就是利用codex自学搭建。"
  },
  "workLead": "个人项目与作品",
  "projects": [
    {
      "kicker": "Short Video",
      "title": "短视频内容",
      "linkText": "进入短视频合集",
      "meta": "Vertical · 00:45",
      "video": "",
      "description": "",
      "collection": [
        {
          "title": "视频 01",
          "bili": "https://www.bilibili.com/video/BV1JGVN62EN2/",
          "video": "",
          "description": "摄影 字节跳动推广项目",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "视频 02",
          "bili": "https://www.bilibili.com/video/BV1zGVN62EYK/",
          "video": "",
          "description": "摄影 字节跳动推广项目",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "视频 03",
          "bili": "https://www.bilibili.com/video/BV1eHVN66EX4/",
          "video": "",
          "description": "摄影 抖音大明星官号",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "视频 04",
          "bili": "https://www.bilibili.com/video/BV15HVN66ERF/",
          "video": "",
          "description": "摄影 抖音大明星官号",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "视频 06",
          "bili": "https://www.bilibili.com/video/BV15HVN66EiQ/",
          "video": "",
          "description": "摄影 抖音电影官号春节档电影宣发",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "视频 05",
          "bili": "https://www.bilibili.com/video/BV1LHVN66EAc/",
          "video": "",
          "description": "摄影",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        }
      ],
      "cover": "assets/images/微信图片_20260525185058_130_2.png",
      "coverBlobKey": "",
      "coverName": "微信图片_20260525185058_130_2.png",
      "coverDataUrl": "",
      "coverFit": "contain",
      "coverX": "50",
      "coverY": "50",
      "coverScale": "1.00",
      "bili": "https://www.bilibili.com/video/BV1JGVN62EN2/",
      "videoBlobKey": "",
      "videoName": ""
    },
    {
      "kicker": "Documentary",
      "title": "纪录片 / 人物故事",
      "linkText": "进入纪录片合集",
      "meta": "Documentary · 03:20",
      "video": "",
      "description": "",
      "collection": [
        {
          "title": "铁轨人生",
          "bili": "https://www.bilibili.com/video/BV174Gq6YEEj/",
          "video": "",
          "description": "摄影 后期",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "火山引擎中科院",
          "bili": "https://www.bilibili.com/video/BV1EWGq6vEKv/",
          "video": "",
          "description": "摄影",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "小学公益案例x火山引擎FORCE",
          "bili": "https://www.bilibili.com/video/BV1EWGq6vELw/",
          "video": "",
          "description": "摄影",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "荣耀案例x火山引擎FORCE",
          "bili": "https://www.bilibili.com/video/BV1BWGq6vEok/",
          "video": "",
          "description": "摄影",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "小学公益案例x火山引擎FORCE",
          "bili": "https://www.bilibili.com/video/BV1EWGq6vEGw/",
          "video": "",
          "description": "摄影",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "视频 06",
          "bili": "",
          "video": "",
          "description": "摄影",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        }
      ],
      "cover": "assets/images/微信图片_20260525185227_132_2.png",
      "coverBlobKey": "",
      "coverName": "微信图片_20260525185227_132_2.png",
      "coverDataUrl": "",
      "coverFit": "contain",
      "coverX": "54",
      "coverY": "7",
      "coverScale": "1.02",
      "bili": "https://www.bilibili.com/video/BV174Gq6YEEj/",
      "videoBlobKey": "",
      "videoName": ""
    },
    {
      "kicker": "Commercial",
      "title": "TVC / 商业广告",
      "linkText": "进入 TVC 合集",
      "meta": "TVC · 00:30",
      "video": "",
      "description": "适合突出布光、镜头质感、产品节奏和商业视觉完成度。",
      "collection": [
        {
          "title": "霸王茶姬 茶香遇",
          "bili": "https://www.bilibili.com/video/BV124Gi6CEPv/",
          "video": "",
          "description": "摄影 后期",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "京东国补X董浩-《老家不老》-北京篇“北京天地宽”",
          "bili": "https://www.bilibili.com/video/BV15YGq6bEVt/",
          "video": "",
          "description": "摄影 ",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "豆包大模型+端到端语音模型",
          "bili": "https://www.bilibili.com/video/BV1ZxGq6PE6L/",
          "video": "",
          "description": "摄影",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "《家风》空军纪委",
          "bili": "https://www.bilibili.com/video/BV1smGZ6zEoy/",
          "video": "",
          "description": "摄影 后期",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "视频 05",
          "bili": "",
          "video": "",
          "description": "摄影 后期",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "视频 06",
          "bili": "",
          "video": "",
          "description": "建议保留最能代表你能力的作品，避免数量太多但重点不清。",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        }
      ],
      "cover": "assets/images/微信图片_20260525184748_127_2.png",
      "coverBlobKey": "",
      "coverName": "微信图片_20260525184748_127_2.png",
      "coverDataUrl": "",
      "coverFit": "contain",
      "coverX": "50",
      "coverY": "0",
      "coverScale": "1.00",
      "bili": "https://www.bilibili.com/video/BV124Gi6CEPv/",
      "videoBlobKey": "",
      "videoName": ""
    },
    {
      "kicker": "Short Film",
      "title": "微电影",
      "linkText": "进入微电影合集",
      "meta": "Film · 06:00",
      "video": "",
      "description": "适合展示叙事镜头、场面调度、情绪剪辑和声音节奏。",
      "collection": [
        {
          "title": "《100》",
          "bili": "https://www.bilibili.com/video/BV1v8Gq6hEdg/",
          "video": "",
          "description": "摄影 后期",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "微短剧《重生之我在非法集资团伙做线人》",
          "bili": "https://www.bilibili.com/video/BV1b6GZ65EUN/",
          "video": "",
          "description": "摄影",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "视频 03",
          "bili": "",
          "video": "",
          "description": "摄影",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "视频 04",
          "bili": "",
          "video": "",
          "description": "适合补充同一类别下的不同风格、不同客户或不同平台版本。",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "视频 05",
          "bili": "",
          "video": "",
          "description": "可以放完整片段、精选片段、幕后花絮或对比版本。",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "视频 06",
          "bili": "",
          "video": "",
          "description": "建议保留最能代表你能力的作品，避免数量太多但重点不清。",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        }
      ],
      "cover": "assets/images/微信图片_20260525184640_126_2.png",
      "coverBlobKey": "",
      "coverName": "微信图片_20260525184640_126_2.png",
      "coverDataUrl": "",
      "coverFit": "contain",
      "coverX": "67",
      "coverY": "32",
      "coverScale": "1.21",
      "bili": "https://www.bilibili.com/video/BV1v8Gq6hEdg/",
      "videoBlobKey": "",
      "videoName": ""
    },
    {
      "kicker": "Promotion",
      "title": "宣传片 / 品牌片",
      "linkText": "进入宣传片合集",
      "meta": "Promo · 01:30",
      "video": "",
      "description": "适合放企业宣传、城市形象、校园宣传、活动回顾等完整项目。",
      "collection": [
        {
          "title": "《豪宅封面 领潮而来》龙湖地产样板间",
          "bili": "https://www.bilibili.com/video/BV1EWGq6vEA2/",
          "video": "",
          "description": "摄影 ",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "时代的工匠",
          "bili": "https://www.bilibili.com/video/BV1j4Gq6YEDb/",
          "video": "",
          "description": "摄影",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "红墙24小时",
          "bili": "https://www.bilibili.com/video/BV1BxGq6PEjT/",
          "video": "",
          "description": "摄影",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "牧马人汽车",
          "bili": "https://www.bilibili.com/video/BV1nfGZ6wEzH/",
          "video": "",
          "description": "摄影 后期",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "云樾府封顶",
          "bili": "https://www.bilibili.com/video/BV1noGZ6YEDw/",
          "video": "",
          "description": "摄影 后期",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "云樾府示范区",
          "bili": "https://www.bilibili.com/video/BV1noGZ6YE6m/",
          "video": "",
          "description": "摄影 后期",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        }
      ],
      "cover": "assets/images/微信图片_20260525192240_140_2.png",
      "coverBlobKey": "",
      "coverName": "微信图片_20260525192240_140_2.png",
      "coverDataUrl": "",
      "coverFit": "contain",
      "coverX": "50",
      "coverY": "18",
      "coverScale": "1.11",
      "bili": "https://www.bilibili.com/video/BV1EWGq6vEA2/",
      "videoBlobKey": "",
      "videoName": ""
    },
    {
      "kicker": "Mini Drama",
      "title": "短剧 / 剧情内容",
      "linkText": "进入短剧合集",
      "meta": "Drama · 02:10",
      "video": "",
      "description": "",
      "collection": [
        {
          "title": "《替换人生》免费看全集",
          "bili": "",
          "video": "",
          "description": "红果短剧完整观看链接",
          "link": "https://novelquickapp.com/s/F0ZkFciEx3g/",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "视频 02",
          "bili": "",
          "video": "",
          "description": "可以填写 B站链接 / BV号，或填写 mp4 直链。",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "视频 03",
          "bili": "",
          "video": "",
          "description": "建议写清项目职责、拍摄/剪辑内容和交付平台。",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "视频 04",
          "bili": "",
          "video": "",
          "description": "适合补充同一类别下的不同风格、不同客户或不同平台版本。",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "视频 05",
          "bili": "",
          "video": "",
          "description": "可以放完整片段、精选片段、幕后花絮或对比版本。",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        },
        {
          "title": "视频 06",
          "bili": "",
          "video": "",
          "description": "建议保留最能代表你能力的作品，避免数量太多但重点不清。",
          "videoBlobKey": "",
          "videoName": "",
          "videoFit": "cover",
          "videoX": "50",
          "videoY": "50",
          "videoScale": "1.00"
        }
      ],
      "cover": "assets/images/微信图片_20260525195647_145_2.jpg",
      "coverBlobKey": "",
      "coverName": "微信图片_20260525195647_145_2.jpg",
      "coverDataUrl": "",
      "coverFit": "contain",
      "coverX": "50",
      "coverY": "50",
      "coverScale": "1.00",
      "bili": "",
      "videoBlobKey": "",
      "videoName": ""
    }
  ],
  "version": "20260526223000"
};
